@startuml Goncourt

class Livre
{
    -string ISBN
    -string titre
    -text resume
    -date date_parution
    -integer nombre_pages
    -string prix_editeur
    -integer nombre_votes
}

class Auteur
{
    -integer id
    -string nom
    -string prenom
    -date date_naissance
    -text biographie
}

class Editeur
{
    -integer id
    -string nom
    -string localisation
}

class Selection{
    -integer id
    -string nom
}

class Jury{
    -integer id
    -string identifiant
    -string mot_de_passe
    -boolean est_president
}

class Personnages{
    -integer id
    -string nom
}

Livre "0..n" <-- "1" Auteur : ecrit >
Livre "0..n" <--"1" Editeur : publie >
Livre "1..n" <--"1" Selection : est selectionne >
Livre "1" -->"0..n" Jury : vote >
Livre "1" -->"1..n" Personnages : comporte >

@enduml
